# Generated by Django 3.2.9 on 2021-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='setor',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Código do produto', max_length=100, null=True, unique=True),
        ),
    ]
